name: Build Docs
on:
  push:
    branches:
      - main
      
jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
        
      - name: Install lerna
        run: npm install lerna -g
      
      - name: Setup npm registry
        run: npm config set registry https://npm.shlab.tech/
        
      - name: Install dependencies
        run: npm install
        
      - name: Build website
        run: npm run-script build
        
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
