name: Build Docs
on:
  push:
    branches:
      - main
      
jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Switch directory
        run: cd ./docs
        
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "{name}=dir::$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Get npm cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        
      - name: Install lerna
        run: npm install lerna -g
      
      - name: Install dependencies
        run: npm install
        
      - name: Build website
        run: npm run-script build
        
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
